GET http://localhost:3002

###Get user by username 
GET http://localhost:3002/users/username/Anita

### Get user by id
GET http://localhost:3002/users/id/61a4e20d1e5ccecbd8765dc7

## Get login

POST  http://localhost:3002/login

Content-Type: application/json

{
    "username": "Anita Reyes",
    "password": "1234z"
}

### , This below won't work because we have not defined the post method for the end point /

## Get user by username
GET h
## post login
POST http://localhost:3002

### But the one below will work because we've defined the endpoint /register
POST http://localhost:3002/register
Content-Type: application/json

{
    "username": "Anita Reyes",
    "password": "1234z"
}

###DELETE Request
DELETE http://localhost:3002/users/15, 16, 17, 18, 19

###PUT request
PUT http://localhost:3002/users
Content-Type: application/json

[
    {
        "id":15,
        "username": "Anita Reyes",
        "password": "1234z"
    },
    {
        "id":16,
        "username": "Anita Reyes",
        "password": "1234z"
    }

]
###

PATCH  http://localhost:3002/users/12
Content-Type: application/json

{
    "username":"Nakityo"
}
